[params]
baseURL = 'https://brandonruizmora.github.io/mi_blog_post/'
languageCode = 'en-us'
title = 'Brandon RuizMora Blog Post'
theme = 'loveit'
relativeURLs = true
canonifyURLs = true

[params.social]
GitHub = 'brandonruizmora'
Linkedin = 'brandon-ruiz-morales-95657613a'
Twitter = 'pandaimpetuoso7'
Instagram = 'pandaimpetuoso7/'